/* Generated by Yosys 0.40+45 (git sha1 dd2195543, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "controller.v:1.1-112.10" *)
module controller(clk, reset, sensor_entrance, sensor_exit, input_password, gate_open, gate_close, alarm_wrong_pin, alarm_block);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  (* src = "controller.v:16.52-16.63" *)
  output alarm_block;
  wire alarm_block;
  (* src = "controller.v:16.23-16.38" *)
  output alarm_wrong_pin;
  wire alarm_wrong_pin;
  (* src = "controller.v:14.7-14.10" *)
  input clk;
  wire clk;
  (* src = "controller.v:19.11-19.17" *)
  wire [2:0] count0;
  (* src = "controller.v:18.11-18.24" *)
  wire [2:0] current_state;
  (* src = "controller.v:16.40-16.50" *)
  output gate_close;
  wire gate_close;
  (* src = "controller.v:16.12-16.21" *)
  output gate_open;
  wire gate_open;
  (* src = "controller.v:15.13-15.27" *)
  input [7:0] input_password;
  wire [7:0] input_password;
  (* src = "controller.v:14.12-14.17" *)
  input reset;
  wire reset;
  (* src = "controller.v:14.19-14.34" *)
  input sensor_entrance;
  wire sensor_entrance;
  (* src = "controller.v:14.36-14.47" *)
  input sensor_exit;
  wire sensor_exit;
  NOT _066_ (
    .A(count0[2]),
    .Y(_005_)
  );
  NOT _067_ (
    .A(count0[1]),
    .Y(_006_)
  );
  NOT _068_ (
    .A(count0[0]),
    .Y(_007_)
  );
  NOT _069_ (
    .A(current_state[2]),
    .Y(_008_)
  );
  NOT _070_ (
    .A(current_state[1]),
    .Y(_009_)
  );
  NOT _071_ (
    .A(current_state[0]),
    .Y(_010_)
  );
  NOT _072_ (
    .A(reset),
    .Y(_011_)
  );
  NOT _073_ (
    .A(input_password[6]),
    .Y(_012_)
  );
  NOT _074_ (
    .A(input_password[1]),
    .Y(_013_)
  );
  NOT _075_ (
    .A(sensor_entrance),
    .Y(_014_)
  );
  NOR _076_ (
    .A(current_state[2]),
    .B(current_state[1]),
    .Y(_015_)
  );
  NAND _077_ (
    .A(_010_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _078_ (
    .A(_014_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _079_ (
    .A(current_state[0]),
    .B(_015_),
    .Y(_018_)
  );
  NOT _080_ (
    .A(_018_),
    .Y(_019_)
  );
  NAND _081_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .Y(_020_)
  );
  NOR _082_ (
    .A(current_state[2]),
    .B(_009_),
    .Y(_021_)
  );
  NOR _083_ (
    .A(current_state[2]),
    .B(_020_),
    .Y(alarm_block)
  );
  NOT _084_ (
    .A(alarm_block),
    .Y(_022_)
  );
  NAND _085_ (
    .A(_008_),
    .B(current_state[0]),
    .Y(_023_)
  );
  NOR _086_ (
    .A(input_password[2]),
    .B(input_password[4]),
    .Y(_024_)
  );
  NOR _087_ (
    .A(input_password[5]),
    .B(input_password[7]),
    .Y(_025_)
  );
  NAND _088_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NOT _089_ (
    .A(_026_),
    .Y(_027_)
  );
  NAND _090_ (
    .A(input_password[0]),
    .B(input_password[3]),
    .Y(_028_)
  );
  NOT _091_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _092_ (
    .A(_012_),
    .B(input_password[1]),
    .Y(_030_)
  );
  NAND _093_ (
    .A(input_password[6]),
    .B(_013_),
    .Y(_031_)
  );
  NOR _094_ (
    .A(_028_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _095_ (
    .A(_029_),
    .B(_030_),
    .Y(_033_)
  );
  NOR _096_ (
    .A(_026_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _097_ (
    .A(_027_),
    .B(_032_),
    .Y(_035_)
  );
  NOR _098_ (
    .A(_023_),
    .B(_034_),
    .Y(_036_)
  );
  NOR _099_ (
    .A(_017_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _100_ (
    .A(reset),
    .B(_037_),
    .Y(_000_)
  );
  NOR _101_ (
    .A(_009_),
    .B(current_state[0]),
    .Y(_038_)
  );
  NAND _102_ (
    .A(_008_),
    .B(_038_),
    .Y(_039_)
  );
  NOT _103_ (
    .A(_039_),
    .Y(gate_open)
  );
  NOR _104_ (
    .A(sensor_exit),
    .B(_039_),
    .Y(_040_)
  );
  NAND _105_ (
    .A(sensor_exit),
    .B(_017_),
    .Y(_041_)
  );
  NOR _106_ (
    .A(_018_),
    .B(_035_),
    .Y(_042_)
  );
  NOR _107_ (
    .A(alarm_block),
    .B(_042_),
    .Y(_043_)
  );
  NAND _108_ (
    .A(_041_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _109_ (
    .A(_040_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _110_ (
    .A(reset),
    .B(_045_),
    .Y(_001_)
  );
  NAND _111_ (
    .A(count0[1]),
    .B(count0[0]),
    .Y(_046_)
  );
  NOT _112_ (
    .A(_046_),
    .Y(_047_)
  );
  NAND _113_ (
    .A(_005_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _114_ (
    .A(_034_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _115_ (
    .A(_022_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _116_ (
    .A(_021_),
    .B(_036_),
    .Y(_051_)
  );
  NOR _117_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOT _118_ (
    .A(_052_),
    .Y(_053_)
  );
  NOR _119_ (
    .A(_007_),
    .B(_053_),
    .Y(_054_)
  );
  NAND _120_ (
    .A(_005_),
    .B(_036_),
    .Y(_055_)
  );
  NAND _121_ (
    .A(_007_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _122_ (
    .A(_011_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _123_ (
    .A(_054_),
    .B(_057_),
    .Y(_002_)
  );
  NOR _124_ (
    .A(_006_),
    .B(_052_),
    .Y(_058_)
  );
  NOR _125_ (
    .A(_047_),
    .B(_055_),
    .Y(_059_)
  );
  NOR _126_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _127_ (
    .A(count0[1]),
    .B(count0[0]),
    .Y(_061_)
  );
  NOR _128_ (
    .A(reset),
    .B(_061_),
    .Y(_062_)
  );
  NOT _129_ (
    .A(_062_),
    .Y(_063_)
  );
  NOR _130_ (
    .A(_060_),
    .B(_063_),
    .Y(_003_)
  );
  NAND _131_ (
    .A(count0[2]),
    .B(_011_),
    .Y(_064_)
  );
  NOR _132_ (
    .A(_052_),
    .B(_064_),
    .Y(_004_)
  );
  NOR _133_ (
    .A(current_state[2]),
    .B(_038_),
    .Y(gate_close)
  );
  NAND _134_ (
    .A(_019_),
    .B(_048_),
    .Y(_065_)
  );
  NOR _135_ (
    .A(_034_),
    .B(_065_),
    .Y(alarm_wrong_pin)
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _136_ (
    .C(clk),
    .D(_000_),
    .Q(current_state[0])
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _137_ (
    .C(clk),
    .D(_001_),
    .Q(current_state[1])
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _138_ (
    .C(clk),
    .D(1'h0),
    .Q(current_state[2])
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _139_ (
    .C(clk),
    .D(_002_),
    .Q(count0[0])
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _140_ (
    .C(clk),
    .D(_003_),
    .Q(count0[1])
  );
  (* src = "controller.v:29.1-37.4" *)
  DFF _141_ (
    .C(clk),
    .D(_004_),
    .Q(count0[2])
  );
endmodule
