/* Generated by Yosys 0.40+45 (git sha1 dd2195543, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "controller.v:1.1-112.10" *)
module controller(clk, reset, sensor_entrance, sensor_exit, input_password, gate_open, gate_close, alarm_wrong_pin, alarm_block);
  (* src = "controller.v:39.1-110.4" *)
  wire _000_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _001_;
  (* src = "controller.v:39.1-110.4" *)
  wire _002_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _003_;
  (* src = "controller.v:39.1-110.4" *)
  wire _004_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _005_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _006_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _007_;
  (* src = "controller.v:39.1-110.4" *)
  wire [2:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire [3:0] _028_;
  wire [1:0] _029_;
  wire _030_;
  wire [1:0] _031_;
  wire _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire [1:0] _037_;
  wire _038_;
  wire _039_;
  wire [7:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire _045_;
  wire [1:0] _046_;
  wire [2:0] _047_;
  wire [2:0] _048_;
  (* src = "controller.v:77.57-77.83" *)
  wire _049_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [11:0] _050_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [11:0] _051_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _052_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _053_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [8:0] _054_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [8:0] _055_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _056_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:97.22-97.32|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:97.22-97.32|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:97.22-97.32|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:77.57-77.83|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:77.57-77.83|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "controller.v:77.57-77.83|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2" *)
  wire [31:0] _062_;
  wire _063_;
  wire _064_;
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _065_;
  (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _066_;
  (* src = "controller.v:16.52-16.63" *)
  output alarm_block;
  wire alarm_block;
  (* src = "controller.v:16.23-16.38" *)
  output alarm_wrong_pin;
  wire alarm_wrong_pin;
  (* src = "controller.v:14.7-14.10" *)
  input clk;
  wire clk;
  (* src = "controller.v:19.11-19.17" *)
  reg [2:0] count0;
  (* src = "controller.v:18.11-18.24" *)
  reg [2:0] current_state;
  (* src = "controller.v:16.40-16.50" *)
  output gate_close;
  wire gate_close;
  (* src = "controller.v:16.12-16.21" *)
  output gate_open;
  wire gate_open;
  (* src = "controller.v:15.13-15.27" *)
  input [7:0] input_password;
  wire [7:0] input_password;
  (* src = "controller.v:22.11-22.21" *)
  wire [2:0] nxt_count0;
  (* src = "controller.v:21.11-21.20" *)
  wire [2:0] nxt_state;
  (* src = "controller.v:14.12-14.17" *)
  input reset;
  wire reset;
  (* src = "controller.v:14.19-14.34" *)
  input sensor_entrance;
  wire sensor_entrance;
  (* src = "controller.v:14.36-14.47" *)
  input sensor_exit;
  wire sensor_exit;
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) current_state[0] <= 1'h0;
    else if (_016_) current_state[0] <= nxt_state[0];
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) current_state[1] <= 1'h0;
    else if (_016_) current_state[1] <= nxt_state[1];
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) current_state[2] <= 1'h0;
    else if (_016_) current_state[2] <= nxt_state[2];
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) count0[0] <= 1'h0;
    else if (_017_) count0[0] <= nxt_count0[0];
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) count0[1] <= 1'h0;
    else if (_017_) count0[1] <= nxt_count0[1];
  (* src = "controller.v:29.1-37.4" *)
  always @(posedge clk)
    if (reset) count0[2] <= 1'h0;
    else if (_017_) count0[2] <= nxt_count0[2];
  assign _018_ = ~input_password[0];
  assign _019_ = ~input_password[3];
  assign _020_ = ~input_password[6];
  assign _061_[2] = ~count0[2];
  assign _021_ = ~current_state[0];
  assign _022_ = ~current_state[1];
  assign _058_[0] = ~count0[0];
  assign _062_[31] = ~_060_[31];
  assign _028_[0] = _018_ |(* src = "controller.v:100.14-100.48" *)  input_password[1];
  assign _028_[1] = input_password[2] |(* src = "controller.v:100.14-100.48" *)  _019_;
  assign _028_[2] = input_password[4] |(* src = "controller.v:100.14-100.48" *)  input_password[5];
  assign _028_[3] = _020_ |(* src = "controller.v:100.14-100.48" *)  input_password[7];
  assign _029_[0] = _028_[0] |(* src = "controller.v:100.14-100.48" *)  _028_[1];
  assign _029_[1] = _028_[2] |(* src = "controller.v:100.14-100.48" *)  _028_[3];
  assign _027_ = _029_[0] |(* src = "controller.v:100.14-100.48" *)  _029_[1];
  assign gate_close = _030_ |(* src = {0{1'b0}} *)  alarm_block;
  assign _031_[0] = _015_ &(* src = {0{1'b0}} *)  _014_;
  assign _031_[1] = _013_ &(* src = {0{1'b0}} *)  _011_;
  assign _017_ = _031_[0] &(* src = {0{1'b0}} *)  _031_[1];
  assign _032_ = _052_[2] |(* src = {0{1'b0}} *)  alarm_block;
  assign _015_ = _032_ |(* src = {0{1'b0}} *)  gate_open;
  assign _014_ = _027_ |(* src = {0{1'b0}} *)  _026_;
  assign _013_ = _046_[0] |(* src = {0{1'b0}} *)  _025_;
  assign _033_[0] = _012_ &(* src = {0{1'b0}} *)  _011_;
  assign _033_[1] = _010_ &(* src = {0{1'b0}} *)  _009_;
  assign _016_ = _033_[0] &(* src = {0{1'b0}} *)  _033_[1];
  assign _034_ = _021_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  _022_;
  assign _025_ = _034_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[2];
  assign _035_ = _046_[0] |(* src = {0{1'b0}} *)  _047_[1];
  assign _012_ = _035_ |(* src = {0{1'b0}} *)  _025_;
  assign _036_ = _021_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[1];
  assign _026_ = _036_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[2];
  assign _037_[0] = _046_[0] |(* src = {0{1'b0}} *)  _004_;
  assign _037_[1] = _047_[1] |(* src = {0{1'b0}} *)  _026_;
  assign _011_ = _037_[0] |(* src = {0{1'b0}} *)  _037_[1];
  assign _038_ = current_state[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  _022_;
  assign _023_ = _038_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[2];
  assign _010_ = sensor_exit |(* src = {0{1'b0}} *)  _023_;
  assign _039_ = sensor_entrance |(* src = {0{1'b0}} *)  _048_[1];
  assign _009_ = _039_ |(* src = {0{1'b0}} *)  _024_;
  assign _049_ = _063_ |(* src = {0{1'b0}} *)  _040_[0];
  assign _041_[0] = _051_[2] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[5];
  assign _041_[1] = _051_[8] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[11];
  assign _053_[2] = _041_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _041_[1];
  assign _042_[0] = _051_[1] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[5];
  assign _042_[1] = _051_[7] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[10];
  assign _053_[1] = _042_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _042_[1];
  assign _043_[0] = _051_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[5];
  assign _043_[1] = _051_[6] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[9];
  assign _053_[0] = _043_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _043_[1];
  assign _044_[0] = alarm_block |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  gate_open;
  assign _030_ = _052_[2] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _052_[3];
  assign _065_ = _044_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _030_;
  assign _056_[2] = _055_[2] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _055_[8];
  assign _056_[1] = _055_[1] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _055_[7];
  assign _056_[0] = _055_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _055_[6];
  assign _066_ = _044_[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _052_[2];
  assign _045_ = current_state[0] |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[1];
  assign _024_ = _045_ |(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *)  current_state[2];
  assign _047_[1] = ~(* src = "controller.v:100.14-100.48" *) _027_;
  assign _052_[3] = ~(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *) _024_;
  assign _052_[2] = ~(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *) _026_;
  assign _048_[1] = sensor_exit &(* src = "controller.v:63.7-63.37" *)  sensor_entrance;
  assign _004_ = _027_ &(* src = "controller.v:77.19-77.83" *)  _049_;
  assign _046_[0] = _027_ &(* src = "controller.v:96.9-96.72" *)  _062_[31];
  assign _008_[2] = _027_ ? (* src = "controller.v:100.14-100.48|controller.v:100.10-102.8" *) 1'hx : 1'h0;
  assign _008_[1] = _027_ ? (* src = "controller.v:100.14-100.48|controller.v:100.10-102.8" *) 1'hx : 1'h1;
  assign _050_[0] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) 1'h1 : _008_[2];
  assign _050_[1] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) 1'h1 : _008_[1];
  assign _050_[2] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) 1'h0 : _008_[2];
  assign _054_[0] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) _058_[0] : 1'hx;
  assign _054_[1] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) _059_[1] : 1'hx;
  assign _054_[2] = _046_[0] ? (* src = "controller.v:96.9-96.72|controller.v:96.5-102.8" *) _059_[2] : 1'hx;
  assign _050_[5] = sensor_exit ? (* src = "controller.v:89.17-89.28|controller.v:89.13-89.49" *) 1'h0 : 1'hx;
  assign _007_[0] = _004_ ? (* src = "controller.v:77.19-77.83|controller.v:77.15-81.18" *) 1'h1 : 1'hx;
  assign _005_[2] = _004_ ? (* src = "controller.v:77.19-77.83|controller.v:77.15-81.18" *) 1'h0 : 1'hx;
  assign _006_[0] = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) 1'h1 : _007_[0];
  assign _006_[2] = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) 1'h0 : _005_[2];
  assign _003_[0] = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) _058_[0] : _005_[2];
  assign _003_[1] = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) _059_[1] : _005_[2];
  assign _003_[2] = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) _059_[2] : _005_[2];
  assign _002_ = _046_[0] ? (* src = "controller.v:73.19-73.82|controller.v:73.15-81.18" *) 1'h0 : _004_;
  assign _050_[6] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _006_[0] : 1'h0;
  assign _050_[7] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _006_[2] : 1'h1;
  assign _050_[8] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _006_[2] : 1'h0;
  assign _054_[6] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _003_[0] : 1'hx;
  assign _054_[7] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _003_[1] : 1'hx;
  assign _054_[8] = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _003_[2] : 1'hx;
  assign _000_ = _027_ ? (* src = "controller.v:70.14-70.48|controller.v:70.10-81.18" *) _002_ : 1'h0;
  assign _050_[9] = _048_[1] ? (* src = "controller.v:63.7-63.37|controller.v:63.3-63.58" *) 1'h1 : _001_[0];
  assign _050_[10] = _048_[1] ? (* src = "controller.v:63.7-63.37|controller.v:63.3-63.58" *) 1'h1 : _001_[2];
  assign _050_[11] = _048_[1] ? (* src = "controller.v:63.7-63.37|controller.v:63.3-63.58" *) 1'h0 : _001_[2];
  assign _001_[0] = sensor_entrance ? (* src = "controller.v:62.11-62.26|controller.v:62.7-62.47" *) 1'h1 : 1'hx;
  assign _001_[2] = sensor_entrance ? (* src = "controller.v:62.11-62.26|controller.v:62.7-62.47" *) 1'h0 : 1'hx;
  assign alarm_block = ~(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *) _025_;
  assign alarm_wrong_pin = _026_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *) 1'h0 : _000_;
  assign gate_open = ~(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10" *) _023_;
  assign nxt_state[0] = _065_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _053_[0] : 1'h0;
  assign nxt_state[1] = _065_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _053_[1] : 1'h0;
  assign nxt_state[2] = _065_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _053_[2] : 1'h0;
  assign nxt_count0[0] = _066_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _056_[0] : 1'hx;
  assign nxt_count0[1] = _066_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _056_[1] : 1'hx;
  assign nxt_count0[2] = _066_ ? (* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _056_[2] : 1'hx;
  assign _063_ = ~(* src = "controller.v:77.57-77.83" *) _064_;
  assign _059_[2] = count0[2] ^(* src = "controller.v:97.22-97.32|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _057_[1];
  assign _060_[31] = count0[2] |(* src = "controller.v:77.57-77.83|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _040_[0];
  assign _040_[0] = _061_[2] &(* src = "controller.v:96.47-96.72|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _057_[1];
  assign _057_[1] = count0[1] &(* src = "controller.v:97.22-97.32|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count0[0];
  assign _064_ = _062_[31] |(* src = {0{1'b0}} *)  _040_[0];
  assign _051_[9] = _050_[9] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[3];
  assign _051_[10] = _050_[10] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[3];
  assign _051_[11] = _050_[11] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[3];
  assign _051_[6] = _050_[6] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _051_[7] = _050_[7] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _051_[8] = _050_[8] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _051_[5] = _050_[5] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  gate_open;
  assign _051_[0] = _050_[0] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _051_[1] = _050_[1] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _051_[2] = _050_[2] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _055_[6] = _054_[6] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _055_[7] = _054_[7] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _055_[8] = _054_[8] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _052_[2];
  assign _055_[0] = _054_[0] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _055_[1] = _054_[1] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _055_[2] = _054_[2] &(* src = "controller.v:0.0-0.0|controller.v:59.3-108.10|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  alarm_block;
  assign _059_[1] = count0[1] ^(* src = "controller.v:77.57-77.83|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  count0[0];
  assign _001_[1] = _001_[2];
  assign _005_[1:0] = { _005_[2], _005_[2] };
  assign _006_[1] = _006_[2];
  assign _007_[2:1] = { _005_[2], _005_[2] };
  assign _008_[0] = _008_[2];
  assign _040_[7:1] = 7'h7f;
  assign _044_[1] = _030_;
  assign _046_[1] = _025_;
  assign { _047_[2], _047_[0] } = { _025_, _046_[0] };
  assign { _048_[2], _048_[0] } = { _024_, sensor_entrance };
  assign _050_[4:3] = { _050_[5], _050_[5] };
  assign _051_[4:3] = { _051_[5], _051_[5] };
  assign _052_[1:0] = { gate_open, alarm_block };
  assign _054_[5:3] = 3'h0;
  assign _055_[5:3] = 3'h0;
  assign { _057_[31:3], _057_[0] } = { 29'h00000000, count0[0] };
  assign _058_[31:1] = { 29'h00000000, count0[2:1] };
  assign { _059_[31:3], _059_[0] } = { 28'h0000000, _057_[2], _058_[0] };
  assign _060_[30:0] = { _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _057_[1], count0[0] };
  assign { _061_[31:3], _061_[1:0] } = { 29'h1fffffff, count0[1:0] };
  assign { _062_[30:3], _062_[1:0] } = { _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _062_[31], _059_[1], _058_[0] };
endmodule
