/* Generated by Yosys 0.40+45 (git sha1 dd2195543, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "cajero.v:1.1-188.10" *)
module controller(CLK, RESET, TARJETA_RECIBIDA, PIN, DIGITO, DIGITO_STB, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, TIPO_TRANS, MONTO, BALANCE_ACTUALIZADO, MONTO_STB, ENTREGAR_DINERO, FONDOS_INSUFICIENTES);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  (* src = "cajero.v:26.12-26.23" *)
  output ADVERTENCIA;
  wire ADVERTENCIA;
  (* src = "cajero.v:28.12-28.31" *)
  output BALANCE_ACTUALIZADO;
  wire BALANCE_ACTUALIZADO;
  (* src = "cajero.v:27.12-27.19" *)
  output BLOQUEO;
  wire BLOQUEO;
  (* src = "cajero.v:19.7-19.10" *)
  input CLK;
  wire CLK;
  (* src = "cajero.v:21.13-21.19" *)
  input [3:0] DIGITO;
  wire [3:0] DIGITO;
  (* src = "cajero.v:19.37-19.47" *)
  input DIGITO_STB;
  wire DIGITO_STB;
  (* src = "cajero.v:29.12-29.27" *)
  output ENTREGAR_DINERO;
  wire ENTREGAR_DINERO;
  (* src = "cajero.v:30.12-30.32" *)
  output FONDOS_INSUFICIENTES;
  wire FONDOS_INSUFICIENTES;
  (* src = "cajero.v:50.11-50.19" *)
  wire [1:0] INTENTOS;
  (* src = "cajero.v:20.14-20.19" *)
  input [31:0] MONTO;
  wire [31:0] MONTO;
  (* src = "cajero.v:19.61-19.70" *)
  input MONTO_STB;
  wire MONTO_STB;
  (* src = "cajero.v:22.14-22.17" *)
  input [15:0] PIN;
  wire [15:0] PIN;
  (* src = "cajero.v:25.12-25.26" *)
  output PIN_INCORRECTO;
  wire PIN_INCORRECTO;
  (* src = "cajero.v:19.12-19.17" *)
  input RESET;
  wire RESET;
  (* src = "cajero.v:19.19-19.35" *)
  input TARJETA_RECIBIDA;
  wire TARJETA_RECIBIDA;
  (* src = "cajero.v:19.49-19.59" *)
  input TIPO_TRANS;
  wire TIPO_TRANS;
  (* src = "cajero.v:51.11-51.27" *)
  wire [2:0] contador_digitos;
  (* src = "cajero.v:48.11-48.24" *)
  wire [3:0] estado_actual;
  (* src = "cajero.v:49.12-49.23" *)
  wire [15:0] pin_interno;
  NOT _303_ (
    .A(contador_digitos[2]),
    .Y(_024_)
  );
  NOT _304_ (
    .A(contador_digitos[1]),
    .Y(_025_)
  );
  NOT _305_ (
    .A(contador_digitos[0]),
    .Y(_026_)
  );
  NOT _306_ (
    .A(pin_interno[11]),
    .Y(_027_)
  );
  NOT _307_ (
    .A(pin_interno[10]),
    .Y(_028_)
  );
  NOT _308_ (
    .A(pin_interno[13]),
    .Y(_029_)
  );
  NOT _309_ (
    .A(pin_interno[9]),
    .Y(_030_)
  );
  NOT _310_ (
    .A(pin_interno[12]),
    .Y(_031_)
  );
  NOT _311_ (
    .A(pin_interno[8]),
    .Y(_032_)
  );
  NOT _312_ (
    .A(pin_interno[7]),
    .Y(_033_)
  );
  NOT _313_ (
    .A(pin_interno[6]),
    .Y(_034_)
  );
  NOT _314_ (
    .A(pin_interno[5]),
    .Y(_035_)
  );
  NOT _315_ (
    .A(pin_interno[4]),
    .Y(_036_)
  );
  NOT _316_ (
    .A(pin_interno[3]),
    .Y(_037_)
  );
  NOT _317_ (
    .A(pin_interno[2]),
    .Y(_038_)
  );
  NOT _318_ (
    .A(pin_interno[1]),
    .Y(_039_)
  );
  NOT _319_ (
    .A(pin_interno[0]),
    .Y(_040_)
  );
  NOT _320_ (
    .A(DIGITO[3]),
    .Y(_041_)
  );
  NOT _321_ (
    .A(DIGITO[2]),
    .Y(_042_)
  );
  NOT _322_ (
    .A(DIGITO[1]),
    .Y(_043_)
  );
  NOT _323_ (
    .A(DIGITO[0]),
    .Y(_044_)
  );
  NOT _324_ (
    .A(estado_actual[3]),
    .Y(_045_)
  );
  NOT _325_ (
    .A(estado_actual[1]),
    .Y(_046_)
  );
  NOT _326_ (
    .A(estado_actual[0]),
    .Y(_047_)
  );
  NOT _327_ (
    .A(RESET),
    .Y(_048_)
  );
  NOT _328_ (
    .A(MONTO[7]),
    .Y(_049_)
  );
  NOT _329_ (
    .A(MONTO_STB),
    .Y(_050_)
  );
  NOT _330_ (
    .A(TARJETA_RECIBIDA),
    .Y(_051_)
  );
  NOT _331_ (
    .A(MONTO[2]),
    .Y(_052_)
  );
  NOT _332_ (
    .A(MONTO[31]),
    .Y(_053_)
  );
  NOT _333_ (
    .A(PIN[0]),
    .Y(_054_)
  );
  NOT _334_ (
    .A(PIN[1]),
    .Y(_055_)
  );
  NOT _335_ (
    .A(PIN[2]),
    .Y(_056_)
  );
  NOT _336_ (
    .A(PIN[4]),
    .Y(_057_)
  );
  NOT _337_ (
    .A(PIN[5]),
    .Y(_058_)
  );
  NOT _338_ (
    .A(PIN[6]),
    .Y(_059_)
  );
  NOT _339_ (
    .A(PIN[7]),
    .Y(_060_)
  );
  NOT _340_ (
    .A(PIN[8]),
    .Y(_061_)
  );
  NOT _341_ (
    .A(PIN[9]),
    .Y(_062_)
  );
  NOT _342_ (
    .A(PIN[11]),
    .Y(_063_)
  );
  NOT _343_ (
    .A(PIN[12]),
    .Y(_064_)
  );
  NOT _344_ (
    .A(PIN[13]),
    .Y(_065_)
  );
  NAND _345_ (
    .A(pin_interno[13]),
    .B(_065_),
    .Y(_066_)
  );
  NAND _346_ (
    .A(_029_),
    .B(PIN[13]),
    .Y(_067_)
  );
  NAND _347_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _348_ (
    .A(pin_interno[1]),
    .B(_055_),
    .Y(_069_)
  );
  NAND _349_ (
    .A(_039_),
    .B(PIN[1]),
    .Y(_070_)
  );
  NAND _350_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _351_ (
    .A(pin_interno[6]),
    .B(_059_),
    .Y(_072_)
  );
  NAND _352_ (
    .A(_034_),
    .B(PIN[6]),
    .Y(_073_)
  );
  NAND _353_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _354_ (
    .A(pin_interno[7]),
    .B(_060_),
    .Y(_075_)
  );
  NAND _355_ (
    .A(_033_),
    .B(PIN[7]),
    .Y(_076_)
  );
  NAND _356_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _357_ (
    .A(pin_interno[11]),
    .B(_063_),
    .Y(_078_)
  );
  NAND _358_ (
    .A(_027_),
    .B(PIN[11]),
    .Y(_079_)
  );
  NAND _359_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _360_ (
    .A(pin_interno[8]),
    .B(_061_),
    .Y(_081_)
  );
  NAND _361_ (
    .A(_032_),
    .B(PIN[8]),
    .Y(_082_)
  );
  NAND _362_ (
    .A(_081_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _363_ (
    .A(pin_interno[0]),
    .B(_054_),
    .Y(_084_)
  );
  NAND _364_ (
    .A(_040_),
    .B(PIN[0]),
    .Y(_085_)
  );
  NAND _365_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _366_ (
    .A(_038_),
    .B(PIN[2]),
    .Y(_087_)
  );
  NAND _367_ (
    .A(pin_interno[9]),
    .B(_062_),
    .Y(_088_)
  );
  NOR _368_ (
    .A(pin_interno[10]),
    .B(PIN[10]),
    .Y(_089_)
  );
  NAND _369_ (
    .A(pin_interno[10]),
    .B(PIN[10]),
    .Y(_090_)
  );
  NOT _370_ (
    .A(_090_),
    .Y(_091_)
  );
  NOR _371_ (
    .A(_089_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _372_ (
    .A(pin_interno[15]),
    .B(PIN[15]),
    .Y(_093_)
  );
  NAND _373_ (
    .A(pin_interno[15]),
    .B(PIN[15]),
    .Y(_094_)
  );
  NOT _374_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _375_ (
    .A(_093_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _376_ (
    .A(pin_interno[14]),
    .B(PIN[14]),
    .Y(_097_)
  );
  NAND _377_ (
    .A(pin_interno[14]),
    .B(PIN[14]),
    .Y(_098_)
  );
  NOT _378_ (
    .A(_098_),
    .Y(_099_)
  );
  NOR _379_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _380_ (
    .A(pin_interno[4]),
    .B(_057_),
    .Y(_101_)
  );
  NAND _381_ (
    .A(_036_),
    .B(PIN[4]),
    .Y(_102_)
  );
  NAND _382_ (
    .A(_101_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _383_ (
    .A(pin_interno[12]),
    .B(_064_),
    .Y(_104_)
  );
  NAND _384_ (
    .A(_031_),
    .B(PIN[12]),
    .Y(_105_)
  );
  NAND _385_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _386_ (
    .A(pin_interno[3]),
    .B(PIN[3]),
    .Y(_107_)
  );
  NAND _387_ (
    .A(pin_interno[3]),
    .B(PIN[3]),
    .Y(_108_)
  );
  NOT _388_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _389_ (
    .A(_107_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _390_ (
    .A(pin_interno[2]),
    .B(_056_),
    .Y(_111_)
  );
  NAND _391_ (
    .A(_030_),
    .B(PIN[9]),
    .Y(_112_)
  );
  NAND _392_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _393_ (
    .A(_035_),
    .B(PIN[5]),
    .Y(_114_)
  );
  NAND _394_ (
    .A(_087_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _395_ (
    .A(_080_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _396_ (
    .A(pin_interno[5]),
    .B(_058_),
    .Y(_117_)
  );
  NAND _397_ (
    .A(_088_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _398_ (
    .A(_113_),
    .B(_118_),
    .Y(_119_)
  );
  NAND _399_ (
    .A(_116_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _400_ (
    .A(_100_),
    .B(_103_),
    .Y(_121_)
  );
  NOR _401_ (
    .A(_071_),
    .B(_092_),
    .Y(_122_)
  );
  NAND _402_ (
    .A(_121_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _403_ (
    .A(_120_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _404_ (
    .A(_074_),
    .B(_110_),
    .Y(_125_)
  );
  NOR _405_ (
    .A(_077_),
    .B(_106_),
    .Y(_126_)
  );
  NAND _406_ (
    .A(_125_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _407_ (
    .A(_068_),
    .B(_086_),
    .Y(_128_)
  );
  NOR _408_ (
    .A(_083_),
    .B(_096_),
    .Y(_129_)
  );
  NAND _409_ (
    .A(_128_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _410_ (
    .A(_127_),
    .B(_130_),
    .Y(_131_)
  );
  NAND _411_ (
    .A(_124_),
    .B(_131_),
    .Y(_132_)
  );
  NOT _412_ (
    .A(_132_),
    .Y(_133_)
  );
  NAND _413_ (
    .A(INTENTOS[1]),
    .B(INTENTOS[0]),
    .Y(_134_)
  );
  NOT _414_ (
    .A(_134_),
    .Y(_135_)
  );
  NAND _415_ (
    .A(_132_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _416_ (
    .A(estado_actual[3]),
    .B(estado_actual[2]),
    .Y(_137_)
  );
  NAND _417_ (
    .A(estado_actual[1]),
    .B(_137_),
    .Y(_138_)
  );
  NAND _418_ (
    .A(estado_actual[1]),
    .B(_047_),
    .Y(_139_)
  );
  NOR _419_ (
    .A(estado_actual[0]),
    .B(_138_),
    .Y(_140_)
  );
  NOT _420_ (
    .A(_140_),
    .Y(_141_)
  );
  NAND _421_ (
    .A(_136_),
    .B(_140_),
    .Y(_142_)
  );
  NOR _422_ (
    .A(_047_),
    .B(_138_),
    .Y(_143_)
  );
  NAND _423_ (
    .A(MONTO_STB),
    .B(_143_),
    .Y(_144_)
  );
  NAND _424_ (
    .A(TIPO_TRANS),
    .B(MONTO_STB),
    .Y(_145_)
  );
  NOT _425_ (
    .A(_145_),
    .Y(_146_)
  );
  NAND _426_ (
    .A(_143_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _427_ (
    .A(MONTO_STB),
    .B(_051_),
    .Y(_148_)
  );
  NAND _428_ (
    .A(_050_),
    .B(TARJETA_RECIBIDA),
    .Y(_149_)
  );
  NAND _429_ (
    .A(_143_),
    .B(_148_),
    .Y(_150_)
  );
  NAND _430_ (
    .A(_145_),
    .B(_149_),
    .Y(_151_)
  );
  NAND _431_ (
    .A(_143_),
    .B(_151_),
    .Y(_152_)
  );
  NOT _432_ (
    .A(_152_),
    .Y(_153_)
  );
  NOR _433_ (
    .A(contador_digitos[1]),
    .B(contador_digitos[0]),
    .Y(_154_)
  );
  NAND _434_ (
    .A(_025_),
    .B(_026_),
    .Y(_155_)
  );
  NOR _435_ (
    .A(_024_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _436_ (
    .A(contador_digitos[2]),
    .B(_154_),
    .Y(_157_)
  );
  NAND _437_ (
    .A(_046_),
    .B(_137_),
    .Y(_158_)
  );
  NOT _438_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _439_ (
    .A(_047_),
    .B(_158_),
    .Y(_160_)
  );
  NAND _440_ (
    .A(estado_actual[0]),
    .B(_159_),
    .Y(_161_)
  );
  NOR _441_ (
    .A(_156_),
    .B(_161_),
    .Y(_162_)
  );
  NAND _442_ (
    .A(_157_),
    .B(_160_),
    .Y(_163_)
  );
  NAND _443_ (
    .A(_045_),
    .B(estado_actual[2]),
    .Y(_164_)
  );
  NOR _444_ (
    .A(estado_actual[1]),
    .B(_164_),
    .Y(BALANCE_ACTUALIZADO)
  );
  NAND _445_ (
    .A(estado_actual[0]),
    .B(BALANCE_ACTUALIZADO),
    .Y(_165_)
  );
  NOT _446_ (
    .A(_165_),
    .Y(ENTREGAR_DINERO)
  );
  NOR _447_ (
    .A(estado_actual[0]),
    .B(_158_),
    .Y(_166_)
  );
  NOT _448_ (
    .A(_166_),
    .Y(_167_)
  );
  NAND _449_ (
    .A(_165_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _450_ (
    .A(TARJETA_RECIBIDA),
    .B(_168_),
    .Y(_169_)
  );
  NAND _451_ (
    .A(_163_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _452_ (
    .A(_153_),
    .B(_170_),
    .Y(_171_)
  );
  NAND _453_ (
    .A(_142_),
    .B(_171_),
    .Y(_172_)
  );
  NAND _454_ (
    .A(RESET),
    .B(_172_),
    .Y(_173_)
  );
  NOT _455_ (
    .A(_173_),
    .Y(_000_)
  );
  NOR _456_ (
    .A(MONTO[0]),
    .B(MONTO[1]),
    .Y(_174_)
  );
  NAND _457_ (
    .A(_052_),
    .B(_174_),
    .Y(_175_)
  );
  NAND _458_ (
    .A(MONTO[3]),
    .B(_175_),
    .Y(_176_)
  );
  NOR _459_ (
    .A(MONTO[4]),
    .B(MONTO[5]),
    .Y(_177_)
  );
  NOT _460_ (
    .A(_177_),
    .Y(_178_)
  );
  NOR _461_ (
    .A(MONTO[6]),
    .B(_178_),
    .Y(_179_)
  );
  NAND _462_ (
    .A(_176_),
    .B(_179_),
    .Y(_180_)
  );
  NAND _463_ (
    .A(MONTO[8]),
    .B(MONTO[9]),
    .Y(_181_)
  );
  NOR _464_ (
    .A(_049_),
    .B(_181_),
    .Y(_182_)
  );
  NAND _465_ (
    .A(_180_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _466_ (
    .A(MONTO[10]),
    .B(MONTO[11]),
    .Y(_184_)
  );
  NAND _467_ (
    .A(_183_),
    .B(_184_),
    .Y(_185_)
  );
  NAND _468_ (
    .A(MONTO[12]),
    .B(_185_),
    .Y(_186_)
  );
  NOT _469_ (
    .A(_186_),
    .Y(_187_)
  );
  NOR _470_ (
    .A(MONTO[17]),
    .B(MONTO[18]),
    .Y(_188_)
  );
  NOR _471_ (
    .A(MONTO[19]),
    .B(MONTO[20]),
    .Y(_189_)
  );
  NAND _472_ (
    .A(_188_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _473_ (
    .A(MONTO[13]),
    .B(MONTO[14]),
    .Y(_191_)
  );
  NOR _474_ (
    .A(MONTO[15]),
    .B(MONTO[16]),
    .Y(_192_)
  );
  NAND _475_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _476_ (
    .A(_190_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _477_ (
    .A(MONTO[29]),
    .B(MONTO[30]),
    .Y(_195_)
  );
  NAND _478_ (
    .A(_053_),
    .B(_195_),
    .Y(_196_)
  );
  NOR _479_ (
    .A(MONTO[22]),
    .B(MONTO[23]),
    .Y(_197_)
  );
  NOR _480_ (
    .A(MONTO[25]),
    .B(MONTO[28]),
    .Y(_198_)
  );
  NOT _481_ (
    .A(_198_),
    .Y(_199_)
  );
  NOR _482_ (
    .A(MONTO[26]),
    .B(MONTO[27]),
    .Y(_200_)
  );
  NOR _483_ (
    .A(MONTO[21]),
    .B(MONTO[24]),
    .Y(_201_)
  );
  NAND _484_ (
    .A(_200_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _485_ (
    .A(_196_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _486_ (
    .A(_194_),
    .B(_203_),
    .Y(_204_)
  );
  NOR _487_ (
    .A(_199_),
    .B(_204_),
    .Y(_205_)
  );
  NAND _488_ (
    .A(_197_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _489_ (
    .A(_187_),
    .B(_206_),
    .Y(_207_)
  );
  NOR _490_ (
    .A(_145_),
    .B(_207_),
    .Y(_208_)
  );
  NOR _491_ (
    .A(_147_),
    .B(_207_),
    .Y(FONDOS_INSUFICIENTES)
  );
  NAND _492_ (
    .A(_132_),
    .B(_134_),
    .Y(_209_)
  );
  NAND _493_ (
    .A(_140_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _494_ (
    .A(_139_),
    .B(_164_),
    .Y(BLOQUEO)
  );
  NAND _495_ (
    .A(_156_),
    .B(_160_),
    .Y(_211_)
  );
  NOT _496_ (
    .A(_211_),
    .Y(_212_)
  );
  NAND _497_ (
    .A(_150_),
    .B(_211_),
    .Y(_213_)
  );
  NOR _498_ (
    .A(BLOQUEO),
    .B(_213_),
    .Y(_214_)
  );
  NAND _499_ (
    .A(_210_),
    .B(_214_),
    .Y(_215_)
  );
  NOR _500_ (
    .A(FONDOS_INSUFICIENTES),
    .B(_215_),
    .Y(_216_)
  );
  NOR _501_ (
    .A(_048_),
    .B(_216_),
    .Y(_001_)
  );
  NOR _502_ (
    .A(_144_),
    .B(_208_),
    .Y(_217_)
  );
  NOR _503_ (
    .A(_133_),
    .B(_141_),
    .Y(PIN_INCORRECTO)
  );
  NAND _504_ (
    .A(_135_),
    .B(PIN_INCORRECTO),
    .Y(_218_)
  );
  NAND _505_ (
    .A(TARJETA_RECIBIDA),
    .B(BALANCE_ACTUALIZADO),
    .Y(_219_)
  );
  NOT _506_ (
    .A(_219_),
    .Y(_220_)
  );
  NOR _507_ (
    .A(BLOQUEO),
    .B(_220_),
    .Y(_221_)
  );
  NAND _508_ (
    .A(_218_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _509_ (
    .A(_217_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _510_ (
    .A(_048_),
    .B(_223_),
    .Y(_002_)
  );
  NOR _511_ (
    .A(DIGITO_STB),
    .B(pin_interno[0]),
    .Y(_224_)
  );
  NAND _512_ (
    .A(DIGITO_STB),
    .B(_044_),
    .Y(_225_)
  );
  NAND _513_ (
    .A(RESET),
    .B(_225_),
    .Y(_226_)
  );
  NOR _514_ (
    .A(_224_),
    .B(_226_),
    .Y(_003_)
  );
  NOR _515_ (
    .A(DIGITO_STB),
    .B(pin_interno[1]),
    .Y(_227_)
  );
  NAND _516_ (
    .A(DIGITO_STB),
    .B(_043_),
    .Y(_228_)
  );
  NAND _517_ (
    .A(RESET),
    .B(_228_),
    .Y(_229_)
  );
  NOR _518_ (
    .A(_227_),
    .B(_229_),
    .Y(_004_)
  );
  NOR _519_ (
    .A(DIGITO_STB),
    .B(pin_interno[2]),
    .Y(_230_)
  );
  NAND _520_ (
    .A(DIGITO_STB),
    .B(_042_),
    .Y(_231_)
  );
  NAND _521_ (
    .A(RESET),
    .B(_231_),
    .Y(_232_)
  );
  NOR _522_ (
    .A(_230_),
    .B(_232_),
    .Y(_005_)
  );
  NOR _523_ (
    .A(DIGITO_STB),
    .B(pin_interno[3]),
    .Y(_233_)
  );
  NAND _524_ (
    .A(DIGITO_STB),
    .B(_041_),
    .Y(_234_)
  );
  NAND _525_ (
    .A(RESET),
    .B(_234_),
    .Y(_235_)
  );
  NOR _526_ (
    .A(_233_),
    .B(_235_),
    .Y(_006_)
  );
  NOR _527_ (
    .A(DIGITO_STB),
    .B(pin_interno[4]),
    .Y(_236_)
  );
  NAND _528_ (
    .A(DIGITO_STB),
    .B(_040_),
    .Y(_237_)
  );
  NAND _529_ (
    .A(RESET),
    .B(_237_),
    .Y(_238_)
  );
  NOR _530_ (
    .A(_236_),
    .B(_238_),
    .Y(_007_)
  );
  NOR _531_ (
    .A(DIGITO_STB),
    .B(pin_interno[5]),
    .Y(_239_)
  );
  NAND _532_ (
    .A(DIGITO_STB),
    .B(_039_),
    .Y(_240_)
  );
  NAND _533_ (
    .A(RESET),
    .B(_240_),
    .Y(_241_)
  );
  NOR _534_ (
    .A(_239_),
    .B(_241_),
    .Y(_008_)
  );
  NOR _535_ (
    .A(DIGITO_STB),
    .B(pin_interno[6]),
    .Y(_242_)
  );
  NAND _536_ (
    .A(DIGITO_STB),
    .B(_038_),
    .Y(_243_)
  );
  NAND _537_ (
    .A(RESET),
    .B(_243_),
    .Y(_244_)
  );
  NOR _538_ (
    .A(_242_),
    .B(_244_),
    .Y(_009_)
  );
  NOR _539_ (
    .A(DIGITO_STB),
    .B(pin_interno[7]),
    .Y(_245_)
  );
  NAND _540_ (
    .A(DIGITO_STB),
    .B(_037_),
    .Y(_246_)
  );
  NAND _541_ (
    .A(RESET),
    .B(_246_),
    .Y(_247_)
  );
  NOR _542_ (
    .A(_245_),
    .B(_247_),
    .Y(_010_)
  );
  NOR _543_ (
    .A(DIGITO_STB),
    .B(pin_interno[8]),
    .Y(_248_)
  );
  NAND _544_ (
    .A(DIGITO_STB),
    .B(_036_),
    .Y(_249_)
  );
  NAND _545_ (
    .A(RESET),
    .B(_249_),
    .Y(_250_)
  );
  NOR _546_ (
    .A(_248_),
    .B(_250_),
    .Y(_011_)
  );
  NOR _547_ (
    .A(DIGITO_STB),
    .B(pin_interno[9]),
    .Y(_251_)
  );
  NAND _548_ (
    .A(DIGITO_STB),
    .B(_035_),
    .Y(_252_)
  );
  NAND _549_ (
    .A(RESET),
    .B(_252_),
    .Y(_253_)
  );
  NOR _550_ (
    .A(_251_),
    .B(_253_),
    .Y(_012_)
  );
  NOR _551_ (
    .A(DIGITO_STB),
    .B(pin_interno[10]),
    .Y(_254_)
  );
  NAND _552_ (
    .A(DIGITO_STB),
    .B(_034_),
    .Y(_255_)
  );
  NAND _553_ (
    .A(RESET),
    .B(_255_),
    .Y(_256_)
  );
  NOR _554_ (
    .A(_254_),
    .B(_256_),
    .Y(_013_)
  );
  NOR _555_ (
    .A(pin_interno[11]),
    .B(DIGITO_STB),
    .Y(_257_)
  );
  NAND _556_ (
    .A(DIGITO_STB),
    .B(_033_),
    .Y(_258_)
  );
  NAND _557_ (
    .A(RESET),
    .B(_258_),
    .Y(_259_)
  );
  NOR _558_ (
    .A(_257_),
    .B(_259_),
    .Y(_014_)
  );
  NOR _559_ (
    .A(DIGITO_STB),
    .B(pin_interno[12]),
    .Y(_260_)
  );
  NAND _560_ (
    .A(DIGITO_STB),
    .B(_032_),
    .Y(_261_)
  );
  NAND _561_ (
    .A(RESET),
    .B(_261_),
    .Y(_262_)
  );
  NOR _562_ (
    .A(_260_),
    .B(_262_),
    .Y(_015_)
  );
  NOR _563_ (
    .A(DIGITO_STB),
    .B(pin_interno[13]),
    .Y(_263_)
  );
  NAND _564_ (
    .A(DIGITO_STB),
    .B(_030_),
    .Y(_264_)
  );
  NAND _565_ (
    .A(RESET),
    .B(_264_),
    .Y(_265_)
  );
  NOR _566_ (
    .A(_263_),
    .B(_265_),
    .Y(_016_)
  );
  NOR _567_ (
    .A(DIGITO_STB),
    .B(pin_interno[14]),
    .Y(_266_)
  );
  NAND _568_ (
    .A(DIGITO_STB),
    .B(_028_),
    .Y(_267_)
  );
  NAND _569_ (
    .A(RESET),
    .B(_267_),
    .Y(_268_)
  );
  NOR _570_ (
    .A(_266_),
    .B(_268_),
    .Y(_017_)
  );
  NOR _571_ (
    .A(pin_interno[15]),
    .B(DIGITO_STB),
    .Y(_269_)
  );
  NAND _572_ (
    .A(_027_),
    .B(DIGITO_STB),
    .Y(_270_)
  );
  NAND _573_ (
    .A(RESET),
    .B(_270_),
    .Y(_271_)
  );
  NOR _574_ (
    .A(_269_),
    .B(_271_),
    .Y(_018_)
  );
  NOR _575_ (
    .A(_158_),
    .B(_162_),
    .Y(_272_)
  );
  NOT _576_ (
    .A(_272_),
    .Y(_273_)
  );
  NAND _577_ (
    .A(INTENTOS[0]),
    .B(_272_),
    .Y(_274_)
  );
  NOR _578_ (
    .A(INTENTOS[0]),
    .B(_212_),
    .Y(_275_)
  );
  NAND _579_ (
    .A(RESET),
    .B(_274_),
    .Y(_276_)
  );
  NOR _580_ (
    .A(_275_),
    .B(_276_),
    .Y(_019_)
  );
  NAND _581_ (
    .A(INTENTOS[1]),
    .B(_273_),
    .Y(_277_)
  );
  NOR _582_ (
    .A(INTENTOS[1]),
    .B(INTENTOS[0]),
    .Y(_278_)
  );
  NOR _583_ (
    .A(_135_),
    .B(_278_),
    .Y(_279_)
  );
  NAND _584_ (
    .A(_212_),
    .B(_279_),
    .Y(_280_)
  );
  NAND _585_ (
    .A(_277_),
    .B(_280_),
    .Y(_281_)
  );
  NAND _586_ (
    .A(RESET),
    .B(_281_),
    .Y(_282_)
  );
  NOT _587_ (
    .A(_282_),
    .Y(_020_)
  );
  NAND _588_ (
    .A(DIGITO_STB),
    .B(_160_),
    .Y(_283_)
  );
  NOR _589_ (
    .A(_026_),
    .B(_283_),
    .Y(_284_)
  );
  NOR _590_ (
    .A(_048_),
    .B(_212_),
    .Y(_285_)
  );
  NAND _591_ (
    .A(_026_),
    .B(_283_),
    .Y(_286_)
  );
  NAND _592_ (
    .A(_285_),
    .B(_286_),
    .Y(_287_)
  );
  NOR _593_ (
    .A(_284_),
    .B(_287_),
    .Y(_021_)
  );
  NAND _594_ (
    .A(_211_),
    .B(_283_),
    .Y(_288_)
  );
  NOT _595_ (
    .A(_288_),
    .Y(_289_)
  );
  NAND _596_ (
    .A(contador_digitos[1]),
    .B(_283_),
    .Y(_290_)
  );
  NOT _597_ (
    .A(_290_),
    .Y(_291_)
  );
  NAND _598_ (
    .A(contador_digitos[1]),
    .B(contador_digitos[0]),
    .Y(_292_)
  );
  NAND _599_ (
    .A(_155_),
    .B(_292_),
    .Y(_293_)
  );
  NOR _600_ (
    .A(_283_),
    .B(_293_),
    .Y(_294_)
  );
  NOR _601_ (
    .A(_291_),
    .B(_294_),
    .Y(_295_)
  );
  NOR _602_ (
    .A(_048_),
    .B(_295_),
    .Y(_022_)
  );
  NOR _603_ (
    .A(_289_),
    .B(_292_),
    .Y(_296_)
  );
  NOR _604_ (
    .A(contador_digitos[2]),
    .B(_296_),
    .Y(_297_)
  );
  NAND _605_ (
    .A(contador_digitos[2]),
    .B(_293_),
    .Y(_298_)
  );
  NAND _606_ (
    .A(DIGITO_STB),
    .B(_298_),
    .Y(_299_)
  );
  NAND _607_ (
    .A(_288_),
    .B(_299_),
    .Y(_300_)
  );
  NAND _608_ (
    .A(RESET),
    .B(_300_),
    .Y(_301_)
  );
  NOR _609_ (
    .A(_297_),
    .B(_301_),
    .Y(_023_)
  );
  NAND _610_ (
    .A(INTENTOS[1]),
    .B(PIN_INCORRECTO),
    .Y(_302_)
  );
  NOR _611_ (
    .A(INTENTOS[0]),
    .B(_302_),
    .Y(ADVERTENCIA)
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _612_ (
    .C(CLK),
    .D(_000_),
    .Q(estado_actual[0])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _613_ (
    .C(CLK),
    .D(_001_),
    .Q(estado_actual[1])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _614_ (
    .C(CLK),
    .D(_002_),
    .Q(estado_actual[2])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _615_ (
    .C(CLK),
    .D(1'h0),
    .Q(estado_actual[3])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _616_ (
    .C(CLK),
    .D(_003_),
    .Q(pin_interno[0])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _617_ (
    .C(CLK),
    .D(_004_),
    .Q(pin_interno[1])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _618_ (
    .C(CLK),
    .D(_005_),
    .Q(pin_interno[2])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _619_ (
    .C(CLK),
    .D(_006_),
    .Q(pin_interno[3])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _620_ (
    .C(CLK),
    .D(_007_),
    .Q(pin_interno[4])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _621_ (
    .C(CLK),
    .D(_008_),
    .Q(pin_interno[5])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _622_ (
    .C(CLK),
    .D(_009_),
    .Q(pin_interno[6])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _623_ (
    .C(CLK),
    .D(_010_),
    .Q(pin_interno[7])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _624_ (
    .C(CLK),
    .D(_011_),
    .Q(pin_interno[8])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _625_ (
    .C(CLK),
    .D(_012_),
    .Q(pin_interno[9])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _626_ (
    .C(CLK),
    .D(_013_),
    .Q(pin_interno[10])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _627_ (
    .C(CLK),
    .D(_014_),
    .Q(pin_interno[11])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _628_ (
    .C(CLK),
    .D(_015_),
    .Q(pin_interno[12])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _629_ (
    .C(CLK),
    .D(_016_),
    .Q(pin_interno[13])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _630_ (
    .C(CLK),
    .D(_017_),
    .Q(pin_interno[14])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _631_ (
    .C(CLK),
    .D(_018_),
    .Q(pin_interno[15])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _632_ (
    .C(CLK),
    .D(_019_),
    .Q(INTENTOS[0])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _633_ (
    .C(CLK),
    .D(_020_),
    .Q(INTENTOS[1])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _634_ (
    .C(CLK),
    .D(_021_),
    .Q(contador_digitos[0])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _635_ (
    .C(CLK),
    .D(_022_),
    .Q(contador_digitos[1])
  );
  (* src = "cajero.v:58.1-77.4" *)
  DFF _636_ (
    .C(CLK),
    .D(_023_),
    .Q(contador_digitos[2])
  );
endmodule
